
# The material type and display name of
# the items to use as buttons in the GUI.
#
buttons:
  prev-button: item_frame "&4&lLast Shelf"
  next-button: item_frame "&2&lNext Shelf"
  up-button:   item_frame "&3&lGo Up"


# The template of the navigation bar
# that is added to the top of each GUI.
#
nav-style:
  pattern: >
    .........
  key:
    '.': black_stained_glass_pane
  up-button: 1


# The default GUI style is shown if there are no containers
# with custom names in the item-frame attached to a bookshelf.
#
default-style:
  0: default-small    # >=  0 items
  15: default-medium  # >= 15 items
  31: default-large   # >= 31 items


# If a container has a custom name that matches one of
# these, it will use that style when displaying its GUI.
#
# *** CUSTOM GUI STYLES MAY GO HERE ***
#
gui-styles:

  default-small:
    pattern: >
      .|-----|.
      .|+++++|.
      .|.....|.
    key:
      '.': black_stained_glass_pane
      '|': blue_stained_glass_pane
      '-': red_stained_glass_pane
      '+': purple_stained_glass_pane
    prev-button: 10
    next-button: 16
    contentIndices: [11, 12, 13, 14, 15]

  default-medium:
    pattern: >
      .|-----|.
      .|.+++.|.
      .|+++++|.
      .|+++++|.
      .|.....|.
    key:
      '.': black_stained_glass_pane
      '|': blue_stained_glass_pane
      '-': red_stained_glass_pane
      '+': purple_stained_glass_pane
    prev-button: 19
    next-button: 25
    contentIndices: [29, 30, 31, 32, 33, 20, 21, 22, 23, 24, 12, 13, 14]

  default-large:
    pattern: >
      .|-----|.
      .|.+++.|.
      .|+++++|.
      .|+++++|.
      .|+++++|.
      .|+++++|.
      .|+++++|.
      .|.+++.|.
      .|.....|.
    key:
      '.': black_stained_glass_pane
      '|': blue_stained_glass_pane
      '-': red_stained_glass_pane
      '+': purple_stained_glass_pane
    prev-button: 37
    next-button: 43
    contentIndices: [66, 67, 68, 56, 57, 58, 59, 60, 47, 48, 49, 50, 51, 38, 39, 40, 41, 42, 29, 30, 31, 32, 33, 20, 21, 22, 23, 24, 12, 13, 14]

  oak-tiny:
    pattern: >
      #-#===#-#
    key:
      '-': oak_planks
      '#': oak_log
      '=': gray_stained_glass_pane
      prev-button: 1
      next-button: 7
      contentIndices: [3, 4, 5]
