
# Messages sent into chat by the plugin.
#
messages:
  tag:         "&f[&bBookShelves&f]&r"
  no-perms:    "&cInsufficient permissions... "
  unknown-cmd: "&cUnknown command: &6/%s %s &c... "
  bad-args:    "&cUsage: &6%s &c..."

# The material type and display name of
# the items to use as buttons in the GUI.
#
buttons:
  prev-button: item_frame "&4&lLast Shelf"
  next-button: item_frame "&2&lNext Shelf"
  up-button:   item_frame "&3&lGo Up"

# A trim added to the top & bottom of each GUI.
#
trim-style:
  pattern: >
    .........
  key:
    '.': black_stained_glass_pane

# The default GUI style is shown if there are no containers
# with custom names in the item-frame attached to a bookshelf
# or if the custom name doesn't match a style defined below.
#
default-style: default-medium

# If a container has a custom name that matches one of
# these, it will use that style when displaying its GUI.
#
# *** CUSTOM GUI STYLES MAY GO HERE ***
#
gui-styles:

  default-small:
    pattern: >
      .|-----|.
      .|+++++|.
      .|.....|.
    key:
      '.': black_stained_glass_pane
      '|': blue_stained_glass_pane
      '-': red_stained_glass_pane
      '+': purple_stained_glass_pane
    prev-button: 10
    next-button: 16
    content: [11, 12, 13, 14, 15]

  default-medium:
    pattern: >
      .|-----|.
      .|.+++.|.
      .|+++++|.
      .|+++++|.
      .|.....|.
    key:
      '.': black_stained_glass_pane
      '|': blue_stained_glass_pane
      '-': red_stained_glass_pane
      '+': purple_stained_glass_pane
    prev-button: 19
    next-button: 25
    content: [12, 13, 14, 20, 21, 22, 23, 24, 29, 30, 31, 32, 33]

  default-large:
    pattern: >
      .|-----|.
      .|.+++.|.
      .|+++++|.
      .|+++++|.
      .|+++++|.
      .|+++++|.
      .|+++++|.
      .|.+++.|.
      .|.....|.
    key:
      '.': black_stained_glass_pane
      '|': blue_stained_glass_pane
      '-': red_stained_glass_pane
      '+': purple_stained_glass_pane
    prev-button: 37
    next-button: 43
    content: [12, 13, 14, 20, 21, 22, 23, 24, 29, 30, 31, 32, 33, 38, 39, 40, 41, 42, 47, 48, 49, 50, 51, 56, 57, 58, 59, 60, 66, 67, 68]

  oak-tiny:
    pattern: >
      #-#===#-#
    key:
      '-': oak_planks
      '#': oak_log
      '=': gray_stained_glass_pane
    prev-button: 1
    next-button: 7
    content: [3, 4, 5]
