main: me.cynadyde.bookshelves.BookShelvesPlugin
name: BookShelves
version: 1.0
api-version: 1.14
description: >
  Remotely view books through bookshelves! Simply attach an item
  frame or a container to the bookshelf.
website: null
authors:
  - Cynadyde (May 2019)
depend:
  - ProtocolLib
commands: {}
permissions:
  bookshelves.*:
    description: "Grants the ability to interact with bookshelves."
    default: true
