main: me.Cynadyde.bookshelves.BookShelvesPlugin
name: BookShelves
version: 0.0.0
api-version: 1.14
description: >
  Remotely view books through bookshelves! Simply attach an item
  frame with either a book or a container of books to the bookshelf.
website: null
authors:
  - Cynadyde (May 2019)
depend:
  - ProtocolLib
commands:
  "bookshelves":
    description: "bookshelves plugin commands."
permissions:
  bookshelves.*:
    description: "Grants all plugin abilities."
    default: op
    children:
      bookshelves.admin: true
      bookshelves.player: true
  bookshelves.admin:
    description: "Grants the ability to reload the plugin's config."
    default: false
  bookshelves.player:
    description: "Grants the ability to interact with bookshelves and view a list of gui templates."
    default: true
