main: me.cynadyde.bookshelfdisplay.BookshelfDisplayPlugin
name: BookshelfDisplay
version: "1.16.4-0"
api-version: "1.14"
description: >
  View galleries of books inside of bookshelves! Simply attach a
  container with your desired items to the side of a bookshelf.
website: https://www.spigotmc.org/resources/bookshelfdisplay.67225/
authors:
  - Cynadyde (May 2019)
depend:
  - ProtocolLib
commands: {}
permissions:
  bookshelfdisplay.*:
    description: "Grants all plugin abilities."
    default: false
    children:
      bookshelfdisplay.view: true
  bookshelfdisplay.view:
    description: "Grants the ability to interact with bookshelves."
    default: true
